# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-19 10:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher_service', '0002_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rewards', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('status', models.BooleanField(default=True)),
                ('volume', models.IntegerField()),
                ('limit', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
